<PlayerSwipeControl>:
    canvas.before:
        Color:
            rgba: self.background_color
        Rectangle:
            pos: self.pos
            size: self.size

        Color:
            rgba: self.border_color
        Line:
            rectangle: self.x, self.y, self.width, self.height
            width: 6

    on_size: self.update_direction_display()
    on_pos: self.update_direction_display()
